### ISSUE TITLE
Error 500 when uploading a correct schema - recipient_name row problem

### ISSUE THREAD

**Issue by evelyn9191** [rossumai/elisctl#62] opened 2019-06-03 11:00 UTC
When using `schema update [id] --format xlsx (see the file attached below)`  I am getting an error message `Error: Invalid response [https://api.elis.rossum.ai/v1/schemas]: <h1>Server Error (500)</h1>`, although the schema is correct. The problem is in the recipient_name row. If deleted or of a new row with the same data is written instead of it, the upload is successful.

[schema.xlsx](https://github.com/rossumai/elisctl/files/3247186/schema.xlsx)

**Comment by KPilnacek** [comment] 2019-06-03 12:56
The problem is that the type of recipient_name is `string ` (there is an extra space).

Will be fixed in https://github.com/rossumai/elisctl/pull/63

**Closed as completed** 2019-06-04 06:13 UTC
Labels: bug

**Comment by KPilnacek** [comment] 2019-06-04 06:14
Version 2.2.0, which trims all whitespace around texts in the xlsx, was released.
